services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80"  # Accès au site WordPress via http://localhost:8000
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress/wp-content/themes:/var/www/html/wp-content/themes
      - ./wordpress/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wordpress/wp-content/uploads:/var/www/html/wp-content/uploads
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    networks:
      - wordpress_net

  db:
    image: mysql:5.7
    container_name: wordpress_db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_net

volumes:
  wordpress_data:
  db_data:

networks:
  wordpress_net:
    driver: bridge
